name:                web-server
version:             0.1.0.0
github:              "githubuser/web-server"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/web-server#readme>

dependencies:
- base >= 4.7 && < 5
- yesod
- persistent
- persistent-sqlite
- persistent-postgresql
- persistent-template
- esqueleto
- transformers
- resourcet
- monad-logger
- conduit
- text
- utf8-string
- dotenv
- time
- aeson
- attoparsec
- resource-pool
- bcrypt
- bytestring
- libjwt-typed
- monad-time
- data-default

library:
  source-dirs: src

executables:
  web-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - web-server

tests:
  web-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - web-server
